import Cabecalho from "@/components/cabecalho/cabecalho";
import Rodape from "@/components/rodape/rodape";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho titulo={"EXEMPLO DE PROPS E TYPES"}
          msg={"Olá Props!!"} 
          usuario={{
            nome:"José",
            email:"josé@email.com"
          }}/>
        {children}
        <Rodape />
      </body>
    </html>
  );
}
